spring.application.name=irs-backend


spring.datasource.url=jdbc:mysql://192.168.1.71:3306/learndev
spring.datasource.username=root
spring.datasource.password=Password@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rajaselvan2003@gmail.com
spring.mail.password=jmtziacgtitptmpe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

whatsapp.phone-number-id=1419172801270458
whatsapp.access-token=EAAem7NHAJD0BSuysPceUOkLk5QArDyoZAfOcSEFwD8GrnuF3kSxqC6peLZCraJL1nqysFqJcV9RqIlRsSZAcL0wnYIGa72gGCtZCGS0G6LvQYelAPPoa8xXxqdwTBox7l2IqtbBE0PRu9KRcjUDNUOItPl7kwyCONiafDkR5LRZC8D1IL3vI66FfG0ZB8ze8gjfU4RROq7anYEflYJQora4ZBizbFhxdjZCLgEFz4cmlf5yLWPoc4hou242nB17Op86U5b3mF0NBQeMEg9UU3Y8G4JtN


server.port=8081